snowflake_demo_project:
  target: trial_acc
  send_anonymous_usage_stats: True
  outputs:
    trial_acc:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: ICEBERG_DB
      warehouse: ICEBERG_WH
      schema: SAMPLE_DB_ICEBERG
      role: accountadmin
      threads: 1
      client_session_keep_alive: false

